version: '3.9'

services:
  ollama-cpu:
    image: ollama/ollama
    profiles: ["cpu"]
    container_name: ollama
    volumes:
      - /tmp/ollamamodels:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "11434:11434"
    networks:
      - llmnetwork
    restart: unless-stopped
   
  ollama-gpu:
    image: ollama/ollama
    profiles: ["gpu"]
    container_name: ollama
    volumes:
      - /tmp/ollamamodels:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "11434:11434"
    networks:
      - llmnetwork
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llmapp:
    image: llmchatbottemplate:latest
    container_name: llmapp
    ports:
      - "8000:8000"
    networks:
      - llmnetwork
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - PORT=8000
    restart: unless-stopped

networks:
  llmnetwork:
    external: true
    name: llmnetwork 