version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - /Users/vijay/ollamamodels:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - llmnetwork
    restart: unless-stopped

  llmapp:
    image: llmchatbottemplate:latest
    container_name: llmapp
    ports:
      - "8000:8000"
    networks:
      - llmnetwork
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - PORT=8000
    depends_on:
      - ollama
    restart: unless-stopped

networks:
  llmnetwork:
    external: true
    name: llmnetwork 