name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install Docker Compose plugin
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.19.0
      with:
        scan-type: 'fs'
        scan-ref: './src'

    - name: Run Bandit (Python security linter)
      run: |
        pip install bandit
        bandit -r src/backend/

    - name: Run npm audit (Node.js security check)
      run: |
        cd src/frontend
        npm install
        npm audit --audit-level=high

    - name: build
      run: cd src; make build

    - name: containers
      run: cd src; make containers-with-cpu; sleep 120

    - name: Run chat API test
      run: |
        curl --request POST \
          --url http://localhost:8000/api/v1/chat \
          --header 'Content-Type: application/json' \
          --header 'User-Agent: insomnia/11.2.0' \
          --data '{
          "context": "climate",
          "question": "weather in usa texas?"
        }'

