name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Docker info
        run: docker --version

      - name: Build containers
        run: |
          cd src
          make build
          make containers-with-cpu

      - name: Run frontend
        run: |
          cd src
          make run 